//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipamento
    {
        public byte Id { get; set; }
        public string Nome { get; set; }
        public string Tipo { get; set; }
        public string Modelo { get; set; }
        public string LicensaSO { get; set; }
        public string LicensaOFF { get; set; }
        public System.DateTime RegData { get; set; }
        public string Descricao { get; set; }
    }
}
